name: Publish README to HTML

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Convert README to HTML
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - run: |
        npm install -g marked
        marked README.md -o index.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
